### ISSUE TITLE
Handle Internal Links to Header in preview tab

### ISSUE THREAD

**Issue by liuderchi** [atom/markdown-preview#314]
- Environment： Atom v1.0.19  win7x64
  - Additional to previous [*relative link issues*] (https://github.com/atom/markdown-preview/issues/85 ""), *Markdown Preview* tab **supporting in-page navigation through headers** would be great.
  - example works fine with *ST3 Markdown Preview* Package :
```
# title 1

  - [Working fine: external url](https://github.com/atom/markdown-preview "url" )
  - [NOT working in preview tab : to title 8.1 using html anchor](#title_8_1)
  - [NOT working in preview tab: to title 8.2 ](#title-82)

# title 2

# title 3

# title 4

# title 5

# title 6

# title 7

# title 8

## title 8.1  <a name="title_8_1"></a>

## title 8.2

- [reference back to title1](#title-1)

```

  - related screenshot
![issue_markdownpreviewsuportinline_link](https://cloud.githubusercontent.com/assets/4994705/10362639/62941238-6de2-11e5-948a-2b7de537e68b.png)

**Comment by rtremmel** [comment]
+1

**Comment by sveinburne** [comment]
+1

**Comment by bradley-fastorientation** [comment]
+ 1

**Comment by JaxCavalera** [comment]
This is still not working for me either so I suspect it is not yet fixed.  Please fix this as it will significantly improve the chances of better quality Documentation being written.

**Comment by ChristopherKing42** [comment]
:+1:

**Comment by snrbrnjna** [comment]
+1

**Comment by bolov** [comment]
This is a MUST HAVE for ToC (Table of Contents). And, at least for me, ToC is a necessity for long but structured documents (there already is another extension to generate it, but it is useless in Atom as in-page navigation doesn't work for the preview)

**Comment by jondoughty** [comment]
+1

**Comment by pdestrais** [comment]
+1, thank for solving this issue

**Comment by binyominzeev** [comment]
+1, I downloaded Atom specifically for having a text editor with navigable ToC

**Comment by Perygryne** [comment]
I've just started experimenting with Atom as a writing environment, and this is the last infuriating hole in an otherwise great idea. BUT I have found a workaround: document-outline provides a side pane, listing headers, which does allow navigation. It's a neat workaround, but this really needs to be built-in.

**Comment by braderhart** [comment]
I'm happy to dig-in for a hack-a-thon if you want to schedule a time.

**Comment by keeyim** [comment]
+1. This isn't working for me; it'd be very helpful if it were fixed.

**Comment by Rendiere** [comment]
+1 this is annoying af

**Comment by morandalex** [comment]
+1 me too, it doesn't work. please solve early

**Comment by 2E0PGS** [comment]
Writing documentation now with a table of contents and amazed this is not a feature already.
+1 for this! May have to move to another package / preview method to test this ToC.

**Comment by gklijs** [comment]
I join the line, as it still isn't working. No idea how hard it is, but if I have some time I might just try myself to fix it.

**Comment by 2E0PGS** [comment]
Update I use markdown preview enhanced now and it works perfectly: https://github.com/shd101wyy/markdown-preview-enhanced

It supports http links and ToC links. Has every feature I need and joint scrolling.

Cheers,
⁣Peter Stevenson (2E0PGS)
http://www.m3pgs.co.uk​

**Comment by allefeld** [comment]
And yet another issue that hasn't been fixed more than four years.
Atom appears to be essentially unmaintained.

**Comment by krfisc88** [comment]
Yep, still doesn't work.

**Comment by AndiLakeC** [comment]
Really a pitty that there is still no workaround existing...
